# Generated by Django 5.2 on 2025-04-25 18:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_type', models.CharField(choices=[('VALIDATION', 'Validation Error'), ('PERMISSION', 'Permission Error'), ('SYSTEM', 'System Error'), ('DATABASE', 'Database Error'), ('OTHER', 'Other Error')], max_length=20)),
                ('description', models.TextField()),
                ('stack_trace', models.TextField(blank=True)),
                ('user_action', models.TextField(blank=True, help_text='What was the user doing?')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
